Repository solongoch/ApertureApp, pull requests merged in 2020-06, with the labels that each got.

#4 Soko first pull request
  models/User.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/users.js
  server.js
Labels: Emily, Priya

#7 Priya
  .gitignore
  Routes/api/posts.js
  Routes/api/profile.js
  Routes/api/users.js
  config/database.js
  config/passport.js
  models/User.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/users.js
  server.js
Labels: PR: Good to Merge, PR: No Conflicts, Soko

#9 -mobile of User.js and users.js, +isEmpty(), +validations for /register
  config/passport.js
  models/User.js
  routes/api/users.js
  validation/is-Empty.js
  validation/register.js
Labels: Emily, PR: Good to Merge, Priya

#10 Priya
  .gitignore
  config/passport.js
  models/Posts.js
  models/Profile.js
  models/User.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/users.js
  validation/is-empty.js
  validation/login.js
  validation/register.js
Labels: Emily, PR: Good to Merge, Soko, enhancement

#11 Priya
  controller/auth.js
  routes/api/auth.js
  routes/api/users.js
  server.js
  validation/changepassword.js
  validation/is-empty.js
  validation/login.js
Labels: Emily, PR: Needs Review, PR: No Conflicts, Soko, enhancement

#12 Emiy
  controller/auth.js
  models/Posts.js
  models/Profile.js
  models/User.js
  package.json
  routes/api/follows.js
  routes/api/posts.js
  routes/api/profile.js
  validation/comment.js
  validation/post.js
Labels: PR: Needs Review, Soko

#13 Soko2
  controller/accessRouteWithWithoutToken.js
  models/Posts.js
  models/User.js
  routes/api/auth.js
  routes/api/follows.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/users.js
  server.js
  validation/login.js
  validation/posts.js
  validation/profile.js
  validation/register.js
Labels: PR: Needs Review

#14 Follow /unfollow User
  controller/accessRouteWithWithoutToken.js
  routes/api/follows.js
  routes/api/posts.js
  routes/api/profile.js
  validation/posts.js
  validation/register.js
Labels: Emily, PR: Good to Merge, Soko, enhancement
