Repository solongoch/ApertureApp, pull requests merged in 2020-08, with the labels that each got.

#52 Soko3
  client/package.json
  client/src/actions/homeActions.js
  client/src/actions/suggestionActions.js
  client/src/actions/types.js
  client/src/components/Auth/LogIn/login.css
  client/src/components/Home/AddComment.js
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Home/Homepage.js
  client/src/components/Home/homepage.css
  client/src/components/Layout/landing.css
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/single-post.css
  client/src/global.css
  client/src/reducers/postReducer.js
  client/src/reducers/profileReducer.js
  routes/api/homepage.js
  routes/api/suggestion.js
  routes/api/users.js
Labels: Emily, PR: Good to Merge, Priya

#53 Priya
  client/src/App.js
  client/src/actions/profileActions.js
  client/src/components/Auth/LogIn/login.css
  client/src/components/EditProfile/ChangePassword.js
  client/src/components/EditProfile/changepassword.css
  client/src/components/Layout/SearchProfile.js
  client/src/components/Layout/landing.css
  client/src/components/Post/CreatePost.js
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  client/src/components/Profile/ProfilePosts.js
  client/src/components/Profile/profile.css
  client/src/components/Profile/profileposts.css
  client/src/components/common/PrivateRoute.js
  client/src/reducers/profileReducer.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Needs Review, Soko, enhancement

#59 Soko3
  client/src/actions/postActions.js
  client/src/actions/profileActions.js
  client/src/actions/types.js
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Post/PostHeader.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/SinglePost.js
  client/src/components/Post/single-post.css
  client/src/components/Profile/ProfilePage.js
  client/src/components/Profile/ProfilePosts.js
  client/src/reducers/postReducer.js
  routes/api/posts.js
Labels: Emily, PR: Good to Merge, Priya

#61 Soko3
  client/src/App.css
  client/src/actions/homeActions.js
  client/src/actions/profileActions.js
  client/src/actions/suggestionActions.js
  client/src/components/Auth/LogIn/login.css
  client/src/components/Home/AddComment.js
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Home/Homepage.js
  client/src/components/Home/homepage.css
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/footer.css
  client/src/components/Layout/navbar.css
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/SinglePost.js
  client/src/components/Post/single-post.css
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  models/Posts.js
  routes/api/posts.js
Labels: Emily, PR: Good to Merge, PR: Needs Review

#63 Priya
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/postActions.js
  client/src/actions/profileActions.js
  client/src/actions/types.js
  client/src/components/Auth/LogIn/login.css
  client/src/components/EditProfile/EditProfile.js
  client/src/components/EditProfile/Uploadavatar.js
  client/src/components/EditProfile/editprofile.css
  client/src/components/Follow/Followers.js
  client/src/components/Follow/Followings.js
  client/src/components/Follow/Unfollow.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/SearchProfile.js
  client/src/components/Post/CreatePost.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostHeader.js
  client/src/components/Post/createpost.css
  client/src/components/Post/single-post.css
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  client/src/components/Profile/ProfilePosts.js
  client/src/components/common/TextFieldGroup.js
  client/src/reducers/postReducer.js
  client/src/reducers/profileReducer.js
  routes/api/profile.js
  routes/api/users.js
  utils/common.js
Labels: Fixes, PR: Needs Review, Soko, enhancement

#71 Priya
  client/src/App.js
  client/src/actions/profileActions.js
  client/src/actions/types.js
  client/src/components/EditProfile/ChangePassword.js
  client/src/components/EditProfile/changepassword.css
  client/src/components/Follow/Data.js
  client/src/components/Follow/Followings.js
  client/src/components/Follow/follow.css
  client/src/components/Layout/Landing.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/SearchProfile.js
  client/src/components/Post/CreatePost.js
  client/src/components/Profile/FollowOrEdit.js
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  client/src/components/Profile/profile.css
  client/src/reducers/profileReducer.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Good to Merge, Soko, bug, duplicate, enhancement

#65 Emily2
  client/src/actions/postActions.js
  client/src/components/Home/Homepage.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostCommentItem.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/postactions.css
  client/src/components/Post/single-post.css
  models/Posts.js
  routes/api/posts.js
Labels: PR: Needs Review, enhancement

#87 Soko3
  client/src/App.css
  client/src/actions/homeActions.js
  client/src/actions/profileActions.js
  client/src/components/EditProfile/editprofile.css
  client/src/components/Follow/Follow.js
  client/src/components/Follow/Followers.js
  client/src/components/Follow/Followings.js
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Home/Homepage.js
  client/src/components/Layout/Navbar.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Profile/FollowOrEdit.js
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  client/src/components/Suggestion/Suggestion.js
  client/src/reducers/profileReducer.js
  routes/api/follows.js
  routes/api/profile.js
  routes/api/suggestion.js
Labels: Emily, PR: Good to Merge, Priya, enhancement

#89 Priya
  client/src/components/EditProfile/ChangePassword.js
  client/src/components/EditProfile/ChangePasswordInputField.js
  client/src/components/EditProfile/EditProfile.js
  client/src/components/EditProfile/changepassword.css
  client/src/components/EditProfile/editprofile.css
  client/src/components/Follow/Follow.js
  client/src/components/Follow/Followers.js
  client/src/components/Follow/Followings.js
  client/src/components/Home/Homepage.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/SearchProfile.js
  client/src/components/Post/CreatePost.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostCommentItem.js
  client/src/components/Post/postactions.css
  client/src/components/Post/single-post.css
  client/src/components/Profile/FollowOrEdit.js
  client/src/components/Profile/ProfileHeader.js
  client/src/reducers/profileReducer.js
  routes/api/follows.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Needs Review, Soko, enhancement

#91 Onload err
  client/src/components/Follow/Follow.js
Labels: Emily, bug

#93 Priya
  client/src/actions/profileActions.js
  client/src/components/Follow/Follow.js
  client/src/components/Follow/Followers.js
  client/src/components/Follow/Unfollow.js
  client/src/components/Follow/follow.css
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Home/Homepage.js
  client/src/components/Home/PostActionsHome.js
  client/src/components/Home/PostCommentItemHome.js
  client/src/components/Post/CreatePost.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostCommentItem.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/postactions.css
  client/src/components/Profile/FollowOrEdit.js
  client/src/components/Suggestion/Suggestion.js
  client/src/reducers/profileReducer.js
  routes/api/follows.js
  routes/api/posts.js
Labels: Emily, Fixes, PR: Good to Merge, PR: No Conflicts, Soko

#100 Soko3
  client/src/actions/profileActions.js
  client/src/actions/types.js
  client/src/components/Follow/Follow.js
  client/src/components/Follow/Followers.js
  client/src/components/Profile/ProfileHeader.js
  client/src/reducers/profileReducer.js
  routes/api/follows.js
  routes/api/profile.js
Labels: Emily, Fixes, Priya, enhancement

#104 Priya
  client/src/actions/profileActions.js
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/single-post.css
  routes/api/profile.js
Labels: Emily, Fixes, PR: Needs Review, Soko

#103 Soko3
  client/src/components/Profile/ProfilePosts.js
  client/src/components/Profile/profileposts.css
  client/src/reducers/profileReducer.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Good to Merge, Priya
