Repository solongoch/ApertureApp, pull requests merged in 2020-07, with the labels that each got.

#15 Priya
  routes/api/follows.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/users.js
Labels: Emily, PR: Good to Merge, PR: No Conflicts, Soko, enhancement

#18 Priya
  README.md
  models/User.js
  routes/api/follows.js
  routes/api/homepage.js
  routes/api/posts.js
  routes/api/profile.js
  server.js
Labels: Emily, PR: Good to Merge, PR: No Conflicts, Soko, enhancement

#19 Testing Issues Fixed
  models/Posts.js
  routes/api/follows.js
  routes/api/posts.js
  routes/api/profile.js
  validation/changepassword.js
  validation/comment.js
  validation/profile.js
Labels: Emily, Fixes, PR: Needs Review, PR: No Conflicts, Soko

#20 extended login expiration
  routes/api/users.js
Labels: PR: Good to Merge, PR: No Conflicts, Priya, Soko

#21 Soko2
  README.md
  routes/api/follows.js
  routes/api/homepage.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/suggestion.js
  routes/api/users.js
  server.js
Labels: Emily, Fixes, PR: Needs Review, Priya

#23 merged PR19 follow and unfollow route in follows.js
  README.md
  routes/api/follows.js
Labels: Fixes, PR: Needs Review, PR: No Conflicts, Priya

#22 Priya
  config/database.js
  routes/api/homepage.js
  routes/api/posts.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Good to Merge, Soko

#24 Soko2 fixed suggestion logic, and added .catch() in posts.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/suggestion.js
Labels: Fixes, PR: Good to Merge, PR: No Conflicts, Priya

#25 Priya
  routes/api/homepage.js
  routes/api/posts.js
  routes/api/profile.js
Labels: Emily, Fixes, PR: Good to Merge, PR: No Conflicts, Soko

#27 Emily2
  routes/api/profile.js
Labels: Fixes, PR: Good to Merge, PR: No Conflicts, Priya, Soko

#28 changed "/posts" route to get all posts from logged in user
  routes/api/posts.js
Labels: Emily, PR: Good to Merge, PR: No Conflicts, Priya

#29 Priya
  routes/api/follows.js
  routes/api/homepage.js
  routes/api/posts.js
  routes/api/profile.js
  routes/api/suggestion.js
Labels: Emily, Fixes, PR: Good to Merge, PR: No Conflicts, Soko

#30 remove password, following, followers from updated profile
  routes/api/profile.js
Labels: Emily, Fixes, PR: Good to Merge, PR: No Conflicts, Priya

#31 Soko2's first PR in Client
  .gitignore
  client/.gitignore
  client/README.md
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/Layout/Footer.js
  client/src/components/Layout/Homepage.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/Profile.js
  client/src/components/Layout/Suggestion.js
  client/src/components/css/footer.css
  client/src/components/css/global.css
  client/src/components/css/homepage.css
  client/src/components/css/navbar.css
  client/src/components/css/profile.css
  client/src/components/css/suggestion.css
  client/src/image/aperture-logo.png
  client/src/image/aperture-logo.svg
  client/src/image/favicon.ico
  client/src/image/find-people-active.svg
  client/src/image/find-people.svg
  client/src/image/heart-active.svg
  client/src/image/heart.svg
  client/src/image/home-active.svg
  client/src/image/home.svg
  client/src/image/img-sq.jpg
  client/src/image/img1.jpg
  client/src/image/search-icon.png
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  package.json
Labels: Emily, PR: Good to Merge, PR: Needs Review, PR: No Conflicts, Priya

#33 Priya
  .gitignore
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/components/Auth/ChangePassword.js
  client/src/components/Auth/Signup.js
  client/src/components/Layout/CreatePost.js
  client/src/components/Layout/Data.js
  client/src/components/Layout/Followers.js
  client/src/components/Layout/Followings.js
  client/src/components/Layout/Footer.js
  client/src/components/Layout/Unfollow.js
  client/src/components/config/key.js
  client/src/components/css/ChangePassword.css
  client/src/components/css/CreatePost.css
  client/src/components/css/Follow.css
  client/src/components/css/Signup.css
  client/src/components/css/Unfollow.css
  client/src/components/css/footer.css
  client/src/components/css/global.css
  client/src/image/Applebadge.png
  client/src/image/aperture-logo.svg
  client/src/image/avatar.png
  client/src/image/avatar2.png
  client/src/image/googleplay.png
  client/src/image/img-sq.jpg
  client/src/image/insta2.png
  client/src/image/logo2.png
Labels: Emily, PR: Good to Merge, Soko

#35 Changed the root path to landing.js
  client/src/App.js
  client/src/components/Auth/Signup.js
  client/src/components/css/changepassword.css
  client/src/components/css/createpost.css
  client/src/components/css/follow.css
  client/src/components/css/landing.css
  client/src/components/css/login.css
  client/src/components/css/signup.css
  client/src/components/css/unfollow.css
Labels: Emily, Fixes, PR: Good to Merge, Soko

#37 Emily2
  .gitignore
  client/package.json
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/types.js
  client/src/components/Auth/EditProfile.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/UploadAvatar.js
  client/src/components/Layout/CreatePost.js
  client/src/components/Layout/Landing.js
  client/src/components/config/Keys.js
  client/src/components/config/key.js
  client/src/components/css/editprofile.css
  client/src/components/css/landing.css
  client/src/components/css/login.css
  client/src/image/loginimage.png
  client/src/reducers/authReducer.js
  client/src/reducers/errorReducer.js
  client/src/reducers/index.js
  client/src/store.js
  client/src/utils/setAuthToken.js
  client/src/validation/is-empty.js
  server.js
Labels: Fixes, PR: Good to Merge, Priya, Soko

#38 Priya
  .gitignore
  client/package.json
  client/src/App.js
  client/src/components/Auth/ChangePassword.js
  client/src/components/Auth/Signup.js
  client/src/components/Layout/CreatePost.js
  client/src/components/Layout/Followers.js
  client/src/components/Layout/Followings.js
  client/src/components/Layout/Profile.js
  client/src/components/Layout/Unfollow.js
  client/src/components/css/changepassword.css
  client/src/components/css/createpost.css
  client/src/components/css/follow.css
  client/src/components/css/signup.css
  client/src/components/css/unfollow.css
  client/src/components/utils/index.js
Labels: Emily, Fixes, PR: Good to Merge, Soko, enhancement

#40 Soko2 PR2 in Client
  client/.gitignore
  client/public/favicon.ico
  client/src/App.js
  client/src/components/Layout/CreatePost.js
  client/src/components/Layout/Homepage.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/Profile.js
  client/src/components/Layout/SinglePost.js
  client/src/components/Layout/Suggestion.js
  client/src/components/css/homepage.css
  client/src/components/css/navbar.css
  client/src/components/css/profile.css
  client/src/components/css/single-post.css
  client/src/components/css/suggestion.css
  client/src/image/favicon.ico
  client/src/image/heart-active.svg
  client/src/image/heart.svg
  client/src/reducers/index.js
  client/src/store.js
Labels: Added Comments, Emily, Fixes, PR: Needs Review, Priya, enhancement

#43 Emily2
  client/.gitignore
  client/src/App.js
  client/src/components/Auth/EditProfile.js
  client/src/components/Auth/Login.js
  client/src/components/EditProfile/CreateProfile.js
  client/src/components/EditProfile/DeleteProfile.js
  client/src/components/EditProfile/EditProfile.js
  client/src/components/Layout/Navbar.js
  client/src/components/css/createprofile.css
  client/src/components/css/editprofile.css
  client/src/reducers/authReducer.js
  package.json
Labels: Added Comments, PR: Needs Review, Priya, Soko, enhancement

#41 Priya
  client/package.json
  client/src/App.js
  client/src/actions/authActions.js
  client/src/components/Auth/Login.js
  client/src/components/Auth/Signup.js
  client/src/components/Auth/SignupInputField.js
  client/src/components/Auth/SignupPasswordField.js
  client/src/components/Layout/CreatePost.js
  client/src/components/config/Keys.js
  client/src/components/css/createpost.css
  client/src/components/utils/index.js
  client/src/reducers/authReducer.js
  client/src/reducers/errorReducer.js
  client/src/reducers/index.js
  client/src/store.js
  client/src/utils/setAuthToken.js
  routes/api/users.js
Labels: Emily, PR: Needs Review, Soko, enhancement

#44 Soko3
  client/src/App.js
  client/src/actions/types.js
  client/src/components/Home/HomeSuggestion.js
  client/src/components/Home/Homepage.js
  client/src/components/Home/homepage.css
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/Profile.js
  client/src/components/Layout/ProfileHeader.js
  client/src/components/Layout/ProfilePosts.js
  client/src/components/Layout/SinglePost.js
  client/src/components/css/navbar.css
  client/src/components/css/single-post.css
  client/src/reducers/authReducer.js
Labels: Emily, Fixes, PR: Good to Merge, Priya, enhancement

#45 Priya
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/postActions.js
  client/src/actions/types.js
  client/src/components/Auth/LogIn/Login.js
  client/src/components/Auth/LogIn/login.css
  client/src/components/Auth/SignUp/Signup.js
  client/src/components/Auth/SignUp/SignupInputField.js
  client/src/components/Auth/SignUp/SignupPasswordField.js
  client/src/components/Auth/SignUp/signup.css
  client/src/components/EditProfile/ChangePassword.js
  client/src/components/EditProfile/CreateProfile.js
  client/src/components/EditProfile/DeleteProfile.js
  client/src/components/EditProfile/EditProfile.js
  client/src/components/EditProfile/changepassword.css
  client/src/components/EditProfile/createprofile.css
  client/src/components/Follow/Data.js
  client/src/components/Follow/Followers.js
  client/src/components/Follow/Followings.js
  client/src/components/Follow/Unfollow.js
  client/src/components/Follow/follow.css
  client/src/components/Follow/unfollow.css
  client/src/components/Home/Homepage.js
  client/src/components/Layout/Footer.js
  client/src/components/Layout/Landing.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/footer.css
  client/src/components/Layout/landing.css
  client/src/components/Layout/navbar.css
  client/src/components/Post/CreatePost.js
  client/src/components/Post/SinglePost.js
  client/src/components/Post/createpost.css
  client/src/components/Post/single-post.css
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePosts.js
  client/src/components/Profile/profile.css
  client/src/components/Suggestion/Suggestion.js
  client/src/components/Suggestion/suggestion.css
  client/src/global.css
  client/src/reducers/authReducer.js
  client/src/reducers/index.js
  client/src/reducers/postReducer.js
Labels: Emily, PR: Good to Merge, Soko, enhancement

#46 Emily2
  client/src/components/Auth/LogIn/Login.js
  client/src/components/Auth/TextFieldGroup.js
  client/src/components/EditProfile/EditProfile.js
  client/src/components/Post/single-post.css
Labels: Fixes, PR: Good to Merge, Priya

#47 Emily2
  client/src/actions/profileActions.js
  client/src/components/EditProfile/CreateProfile.js
  client/src/components/EditProfile/DeleteProfile.js
  client/src/components/EditProfile/createprofile.css
  client/src/components/Post/PostActions.js
  client/src/components/Post/PostComment.js
  client/src/components/Post/PostCommentSection.js
  client/src/components/Post/PostHeader.js
  client/src/components/Post/PostSidebar.js
  client/src/components/Post/SinglePost.js
Labels: PR: Good to Merge, Priya, Soko, enhancement

#49 PR-49
  client/src/actions/profileActions.js
  client/src/components/EditProfile/DeleteProfile.js
  client/src/components/EditProfile/EditProfile.js
  client/src/components/EditProfile/Uploadavatar.js
  client/src/components/EditProfile/editprofile.css
  client/src/reducers/profileReducer.js
  models/User.js
  routes/api/profile.js
  routes/api/users.js
  utils/common.js
  validation/profile.js
Labels: Emily, Fixes, PR: Good to Merge, PR: No Conflicts, Soko, enhancement

#50 Soko3
  client/src/App.css
  client/src/App.js
  client/src/actions/authActions.js
  client/src/actions/profileActions.js
  client/src/actions/types.js
  client/src/components/Layout/Navbar.js
  client/src/components/Layout/SearchProfile.js
  client/src/components/NotFound/NotFound.js
  client/src/components/Profile/ProfileHeader.js
  client/src/components/Profile/ProfilePage.js
  client/src/components/Profile/ProfilePosts.js
  client/src/reducers/index.js
  client/src/reducers/profileReducer.js
  client/src/store.js
Labels: Added Comments, Emily, PR: Good to Merge, Priya, enhancement
